default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: raksh_crackers_development
  host: localhost
  port: 5432
  username: postgres
  password: password

test:
  <<: *default
  database: raksh_crackers_test
  username: postgres
  password: password

production:
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>

